In [42]:
import numpy as np
list_n = np.array([[1, 2, 3]])

In [43]:
list_n

array([[1, 2, 3]])

In [44]:
list_n = np.append(list_n, [[4,5,6]], axis=0)
list_n

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
list_a = np.array([1, 2, 3])
list_b = np.array([1, 2, 3])
list = np.append(list_a, list_b,).reshape(2,3)
list

array([[1, 2, 3],
       [1, 2, 3]])

In [79]:
list_a = np.array([1, 2, 3])
list_b = np.array([4, 2, 3])
list_for = list_a 
for i in range(10):
    list_for = np.append(list_for, list_b,).reshape(i+2,3)

In [80]:
list_for

array([[1, 2, 3],
       [4, 2, 3],
       [4, 2, 3],
       [4, 2, 3],
       [4, 2, 3],
       [4, 2, 3],
       [4, 2, 3],
       [4, 2, 3],
       [4, 2, 3],
       [4, 2, 3],
       [4, 2, 3]])

In [71]:
list_a

array([1, 2, 3])